const image_links = [
  "edward_chair.jpg",
  "edward_cheeze.jpg",
  "edward_christmas.jpg",
  "edward_curl.jpg",
  "edward_grump.jpg",
  "edward_king.jpg",
  "edward_lay.jpg",
  "edward_leg.jpg",
  "edward_majestic.jpg",
  "edward_nap.jpg",
  "edward_railing.jpg",
  "edward_red.jpg",
  "edward_sit.jpg",
  "edward_sleep.jpg",
  "edward_sprawl.jpg",
  "edward_regal.jpg",
  "edward_grumpy.jpg",
  "edward_chill.jpg",
  "edward_stoic.jpg",
  "edward_pensive.jpg",
  "edward_flog.jpg",
  "edward_despair",
  "edward_present.jpg",
  "edward_slim.jpg",
  "edward_slept.jpg",
  "edward_lounge.jpg"
]

export default image_links
